In [2]:
import numpy as np

In [3]:
#cria uma matriz unidimensional
mt = np.array([15,35,25,10,5])
print(mt)
print(type(mt))

[15 35 25 10  5]
<class 'numpy.ndarray'>


In [6]:
#cria o array com um tipo específico
#cria um array como um float 64-bit
mtfloat = np.array([1,3,4],dtype=np.float64)
print(mtfloat)
print(type(mtfloat))

#cria um array como um int 32-bit
mtint = np.array([2,3,8],dtype=np.int32)
print(mtint)
print(type(mtint))


[1. 3. 4.]
<class 'numpy.ndarray'>
[2 3 8]
<class 'numpy.ndarray'>


In [5]:
#muda o tipo do array
#pode-se transformar o tipo de dados do arraywe can transform array data types
mtnew = np.array([1.4, 5.8, -5.9, 45.98, 3.99999])
print(mtnew)

#quando transforma o valor de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4      5.8     -5.9     45.98     3.99999]
[ 1  5 -5 45  3]


In [6]:
#pode-se fazer ao contrário também
mt5 = np.array([1, 2, 3, 4, 5])
print(mt5)
mt6 = mt5.astype(np.float64)
print(mt6)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [7]:
# mais de uma dimensão
# cria uma array bidimensional
mt7 = np.array([[1, 2, 3],
               [7, 8, 9],
               [15, 38, 43]])
print(mt7)

[[ 1  2  3]
 [ 7  8  9]
 [15 38 43]]


In [13]:
#cria um array tipado vazio
# vazio significa não inicilizado, não vazio
empty = np.empty([3,2],dtype = int)
print(empty)
print("-----------------")

#cria uma matriz 4X3 com zeros
zeros = np.zeros([4,3])
print(zeros)
print("-----------------")

#com valores igual a ume
ones = np.ones([4,3])
print(ones)
print("-----------------")

#cria uma matriz quadrada com a diagona principal com valores igual a 1 e os outros valores igual a zero
diagonal = np.eye(5)
print(diagonal)

[[ 1886745605 -1720556180]
 [ 1912602625         410]
 [      98418     8090112]]
-----------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
#valores aleatórios entre 0 e 1
rnd = np.random.random((5))
print(rnd)
print("-----------------")

#distribuição normal de valores com numeros negaticosrandom values normal distribution with negatives numbers
rnd2 = np.random.randn((5))
print(rnd2)
print("-----------------")

#valores aleatorios 3X4
rnd3 = (10*np.random.random((3,4)))
print(rnd3)

[0.23023511 0.60192028 0.98733124 0.25596658 0.12373208]
-----------------
[-1.80089216  0.25523357 -0.52495381  0.72547599 -2.51450543]
-----------------
[[0.49269447 9.49323138 7.99408344 7.30677932]
 [4.21611101 7.00853132 0.18064993 1.93497044]
 [1.41271112 5.83944102 8.67009998 4.50979278]]


In [15]:
#outra maneira de gerar valores aleatoriosanother way to generate random numbers
gnr = np.random.default_rng(1)
rnd4 = gnr.random (3)
print(rnd4)

#gerar inteiros
rnd5 = gnr.integers(10, size=(3,4))
print(rnd5)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [63]:
#unique remove repetições
j = np.array([11, 12, 9, 9, 15, 14, 14, 13, 13, 1, 1, 1, 13, 22, 22, 145, 145, 1, 2])
j = np.unique(j)
print(j)

[  1   2   9  11  12  13  14  15  22 145]


In [16]:
#funções especificas
#cria um array bidimensional com o nome de k
k = np.array([[1, 5, 45],
              [2, 10, 90],
              [8, 40, 21]])

#mostra k
print(k)

#mostra um elemento específico de k
print(k[0][2])

#mostra a dimensão de k
print(k.shape)

[[ 1  5 45]
 [ 2 10 90]
 [ 8 40 21]]
45
(3, 3)


In [17]:
#funções matemáticas
#mostra o maior valor do array k
print(k.max())

#mostra o menor valor
print(k.min())

#soma os valores 
print(k.sum())

#média dos valoresaverage between the values
print(k.mean())

#desvio padrão
# print(k.std())

90
1
222
24.666666666666668


In [18]:
#função universal , aplicada a todos os elementos
#mostra a raiz quadrada de todos os elementos 
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

#valore exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [19]:
#extração de todos elementos
m = np.array([1, 2, 3, 4, 5, 6])

#mostra o elemento da segunda posição
print(m[1])
print("--------")

#mostra a posição entre 0 e 1, dois elementos
print(m[0:2])
print("--------")

#mostra a partir do index 1 para frente
print(m[1:])
print("--------")

#mostra a penultima sição até o fim
print(m[-3:])

2
--------
[1 2]
--------
[2 3 4 5 6]
--------
[4 5 6]


In [20]:
#extrção de linhas e colunas
x = np.array([[4, 5], [6, 1], [7, 4]])
print(x)
print("-------")

#primeira linha, todas as colunas 
row1 = x[0, :]
print(row1)
print("-------")

#segunda linha
row2 = x[1, :]
print(row2)
print("-------")

#terceira linha
row3 = x[2, :]
print(row3)
print("-------")

#todas linhas primeira coluna
c1 = x[ :, 0]
print(c1)
print("-------")

#segnda coluna
c2 = x[ :, 1]
print(c2)
print("-------")


[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[7 4]
-------
[4 6 7]
-------
[5 1 4]
-------


In [21]:
n = np.array([[1, 2],
              [3, 4]])
m = np.array([[1, 1],
              [1, 1]])

#adição
a = n + m
print(a)
print("-------")

#multiplicação
b = n * m
print(b)
print("-------")

p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p+q)

[[2 3]
 [4 5]]
-------
[[1 2]
 [3 4]]
-------
[[3 3]
 [5 5]
 [7 7]]


In [22]:
# traposição, rearranja os 15 elemento de 0 a 14 em 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))
print(f)
print("-------")

#matriz transposta
s = f.T
print(s)
print("-------")

#outra maneira de fazer a transposição
r = np.arange(15).reshape((3, 5))
print(r)
print("-------")
s = r.transpose((1,0))
print(s)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
-------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [23]:
#expressão logica usando where
v = np.random.randn(4, 4)
print(v)

#criando uma matriz de valor booleano baseado no array v
y = (v > 0)
print(y)

#criando uma matriz com valores -1 e 1 baseado no array z
z = np.where(y > 0, 1, -1)
print(z)

[[ 5.35665125e-02  4.23432728e-01 -1.68308842e+00 -1.81249421e+00]
 [ 4.59588113e-01  8.36807484e-01 -2.03025996e-03 -3.13197750e-01]
 [ 1.61613598e-02 -2.83947551e-01  9.20414090e-01  6.22111806e-01]
 [ 4.33058393e-01 -3.15222350e-01 -7.82865118e-02 -2.41961857e+00]]
[[ True  True False False]
 [ True  True False False]
 [ True False  True  True]
 [ True False False False]]
[[ 1  1 -1 -1]
 [ 1  1 -1 -1]
 [ 1 -1  1  1]
 [ 1 -1 -1 -1]]
