In [1]:
import numpy as np

In [4]:
#create an unidimensional matrix
mt = np.array([15,35,25,10,5])
print(mt)
print(type(mt))

[15 35 25 10  5]
<class 'numpy.ndarray'>


In [6]:
#create the array with a specific type
#create the array as a 64-bit float
mtfloat = np.array([1,3,4],dtype=np.float64)
print(mtfloat)
print(type(mtfloat))

#create the array as a 32-bit int
mtint = np.array([2,3,8],dtype=np.int32)
print(mtint)
print(type(mtint))


[1. 3. 4.]
<class 'numpy.ndarray'>
[2 3 8]
<class 'numpy.ndarray'>


In [10]:
#change array type
#we can transform array data types
mtnew = np.array([1.4, 5.8, -5.9, 45.98, 3.99999])
print(mtnew)

#when we transform from float to int the values are truncated
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4      5.8     -5.9     45.98     3.99999]
[ 1  5 -5 45  3]


In [11]:
#we can do the reverse too
mt5 = np.array([1, 2, 3, 4, 5])
print(mt5)
mt6 = mt5.astype(np.float64)
print(mt6)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [13]:
# more than one dimension
# create a two-dimensional array
mt7 = np.array([[1, 2, 3],
               [7, 8, 9],
               [15, 38, 43]])
print(mt7)

[[ 1  2  3]
 [ 7  8  9]
 [15 38 43]]


In [18]:
#create typed empty arrays
#empty means uninitialized, not empty
empty = np.empty([3,2],dtype = int)
print(empty)
print("-----------------")

#create a 4x3 matrix with zero values
zeros = np.zeros([4,3])
print(zeros)
print("-----------------")

#with values equal to one
ones = np.ones([4,3])
print(ones)
print("-----------------")

#create square matrix with main diagonal with values 1 and the other values zero
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1074266112]
 [         0 1074790400]]
-----------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [57]:
#random values between 0 and 1
rnd = np.random.random((5))
print(rnd)
print("-----------------")

#random values normal distribution with negatives numbers
rnd2 = np.random.randn((5))
print(rnd2)
print("-----------------")

#random values 3x4
rnd3 = (10*np.random.random((3,4)))
print(rnd3)

[0.55339968 0.69068039 0.2668321  0.12284469 0.44737347]
-----------------
[-0.19406561 -0.76316812  1.01067308  0.04661598  0.84661175]
-----------------
[[0.59031313 0.0276342  0.33937053 2.47316417]
 [8.00347228 2.76973877 8.96192359 5.5326496 ]
 [8.81799466 8.55140031 1.32880004 3.7399077 ]]


In [61]:
#another way to generate random numbers
#seed use
gnr = np.random.default_rng(1)
rnd4 = gnr.random (3)
print(rnd4)

#generate integers
rnd5 = gnr.integers(10, size=(3,4))
print(rnd5)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [63]:
#unique removes repetitions
j = np.array([11, 12, 9, 9, 15, 14, 14, 13, 13, 1, 1, 1, 13, 22, 22, 145, 145, 1, 2])
j = np.unique(j)
print(j)

[  1   2   9  11  12  13  14  15  22 145]


In [64]:
#specific functions
#creates a two-dimensional array named as k
k = np.array([[1, 5, 45],
              [2, 10, 90],
              [8, 40, 21]])

#shows k
print(k)

#shows an specific element from k
print(k[0][2])

#shows k dimensions
print(k.shape)

[[ 1  5 45]
 [ 2 10 90]
 [ 8 40 21]]
45
(3, 3)


In [65]:
#mathematical functions
#Shows the largest value of array k
print(k.max())

#shows the lower value 
print(k.min())

#sum the values 
print(k.sum())

#average between the values
print(k.mean())

#standard deviation
print(k.std())

90
1
222
24.666666666666668
27.656624683588717


In [70]:
#universal functions, applied to all elements
#shows the square root of all elements 
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

#exponential values of all elements
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [72]:
#extraction of elements
m = np.array([1, 2, 3, 4, 5, 6])

#shows the second postions element
print(m[1])
print("--------")

#shows position 0 and 1, two elements
print(m[0:2])
print("--------")

#shows the index 1 forward
print(m[1:])
print("--------")

#shows the penultimate position to the end
print(m[-3:])

2
--------
[1 2]
--------
[2 3 4 5 6]
--------
[4 5 6]


In [80]:
#columns and rows extraction
x = np.array([[4, 5], [6, 1], [7, 4]])
print(x)
print("-------")

#first row, all columns 
row1 = x[0, :]
print(row1)
print("-------")

#second row
row2 = x[1, :]
print(row2)
print("-------")

#third row
row3 = x[2, :]
print(row3)
print("-------")

#all rows, first column
c1 = x[ :, 0]
print(c1)
print("-------")

#second column
c2 = x[ :, 1]
print(c2)
print("-------")


[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[7 4]
-------
[4 6 7]
-------
[5 1 4]
-------


In [84]:
n = np.array([[1, 2],
              [3, 4]])
m = np.array([[1, 1],
              [1, 1]])

#addition 
a = n + m
print(a)
print("-------")

#multiplication
b = n * m
print(b)
print("-------")

p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p+q)

[[2 3]
 [4 5]]
-------
[[1 2]
 [3 4]]
-------
[[3 3]
 [5 5]
 [7 7]]


In [89]:
# transpose, rearranges a set of 15 elements from 0 to 14
# in 3 rows and 5 columns.
f = np.arange(15).reshape((3,5))
print(f)
print("-------")

#transposed matrix
s = f.T
print(s)
print("-------")

#another way to do the same thing
r = np.arange(15).reshape((3, 5))
print(r)
print("-------")
s = r.transpose((1,0))
print(s)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
-------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [124]:
#logical expressions using WHERE
v = np.random.randn(4, 4)
print(v)

#creating a boolean values matrix based on array v
y = (v > 0)
print(y)

#creating a matrix with values -1 and 1 based on array z
z = np.where(y > 0, 1, -1)
print(z)

[[-0.83390957  0.3817686  -0.04498323 -0.57173716]
 [ 0.18279954  0.47703078 -1.04513877  0.86705066]
 [-0.37615438 -1.26532927 -0.40655895  0.76972168]
 [ 0.13170243  2.26665321 -0.92759991 -0.18538075]]
[[False  True False False]
 [ True  True False  True]
 [False False False  True]
 [ True  True False False]]
[[-1  1 -1 -1]
 [ 1  1 -1  1]
 [-1 -1 -1  1]
 [ 1  1 -1 -1]]
